title: HelmHUD
description: A heads-up display for sportswear!
theme: minima
#remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-paginate
show_downloads: false
paginate: 2
basewebsite: /HelmHUD
permalink: date